nsPrefix: onap
pullPolicy: Always
nodePortPrefix: 302
image:
  readiness: oomk8s/readiness-check:1.0.0
  mysqlServer: mysql/mysql-server:5.6
  dgbuilderSdnc: nexus3.onap.org:10001/onap/ccsdk-dgbuilder-image:v0.1.1
  sdnc: nexus3.onap.org:10001/onap/sdnc-image:v1.2.2
  admportalSdnc: nexus3.onap.org:10001/onap/admportal-sdnc-image:v1.2.2
  ueblistener: nexus3.onap.org:10001/onap/sdnc-ueb-listener-image:v1.2.2
  dmaaplistener: nexus3.onap.org:10001/onap/sdnc-dmaap-listener-image:v1.2.2
  filebeat: docker.elastic.co/beats/filebeat:5.5.0
