osdfPlacementSOUsername: {{ .Values.config.osdfPlacementSOUsername }}
osdfPlacementSOPassword: {{ .Values.config.osdfPlacementSOPassword }}

osdfCMSchedulerUsername: {{ .Values.config.osdfCMSchedulerUsername }}
osdfCMSchedulerPassword: {{ .Values.config.osdfCMSchedulerPassword }}

soUsername: {{ .Values.config.soUsername }}
soPassword: {{ .Values.config.soPassword }}

conductorUrl: {{ .Values.config.conductorUrl }}
conductorUsername: {{ .Values.config.conductorUsername }}
conductorPassword: {{ .Values.config.conductorPassword }}
conductorPingWaitTime: {{ .Values.config.conductorPingWaitTime }}
conductorMaxRetries: {{ .Values.config.conductorMaxRetries }}

policyPlatformUrl: {{ .Values.config.policyPlatformUrl }}
policyPlatformEnv: {{ .Values.config.policyPlatformEnv }}
policyPlatformUsername: {{ .Values.config.policyPlatformUsername }}
policyPlatformPassword: {{ .Values.config.policyPlatformPassword }}
policyClientUsername: {{ .Values.config.policyClientUsername }}
policyClientPassword: {{ .Values.config.policyClientPassword }}

messageReaderHosts: {{ .Values.config.messageReaderHosts }}
messageReaderTopic: {{ .Values.config.messageReaderTopic }}
messageReaderAafUserId: {{ .Values.config.messageReaderAafUserId }}
messageReaderAafPassword: {{ .Values.config.messageReaderAafPassword }}

sdcUrl: {{ .Values.config.sdcUrl }}
sdcUsername: {{ .Values.config.sdcUsername }}
sdcPassword: {{ .Values.config.sdcPassword }}
sdcONAPInstanceID: {{ .Values.config.sdcONAPInstanceID }}

osdfPlacementUsername: {{ .Values.config.osdfPlacementUsername }}
osdfPlacementPassword: {{ .Values.config.osdfPlacementPassword }}
