#{{ if not .Values.disableRobotRobot }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: robot
  namespace: "{{ .Values.nsPrefix }}-robot"
spec:
  selector:
    matchLabels:
      app: robot
  template:
    metadata:
       labels:
        app: robot
       name: robot
    spec:
      containers:
      - command:
        - bash
        - "-c"
        - |
          lighttpd -D -f /etc/lighttpd/lighttpd.conf
        image: {{ .Values.image.testsuite }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        name: robot
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: robot-resources-asdc-interface
          mountPath: /var/opt/OpenECOMP_ETE/robot/resources/asdc_interface.robot
        - name: robot-resources-sdnc-interface
          mountPath: /var/opt/OpenECOMP_ETE/robot/resources/sdngc_interface.robot
        - name: robot-eteshare
          mountPath: /share
        - name: lighttpd-authorization
          mountPath: /etc/lighttpd/authorization
        ports:
        - containerPort: 88
        readinessProbe:
          tcpSocket:
            port: 88
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: robot-resources-sdnc-interface
          hostPath:
            path: /dockerdata-nfs/{{ .Values.nsPrefix }}/robot/robot/resources/sdngc_interface.robot
        - name: robot-resources-asdc-interface
          hostPath:
            path: /dockerdata-nfs/{{ .Values.nsPrefix }}/robot/robot/resources/asdc_interface.robot
        - name: robot-eteshare
          hostPath:
            path: /dockerdata-nfs/{{ .Values.nsPrefix }}/robot/eteshare
        - name: lighttpd-authorization
          hostPath:
            path: /dockerdata-nfs/{{ .Values.nsPrefix }}/robot/authorization
      imagePullSecrets:
      - name: "{{ .Values.nsPrefix }}-docker-registry-key"
#{{ end }}