nsPrefix: onap
pullPolicy: Always
disableDcae: false
nginx:
  repository: nginx
  tag: stable
heat_bootstrap:
  repository: ubuntu
  tag: xenial

# Those are the IPs of the nodes in your K8S cluster.
# You don't need to touch this is you have just one node.
# If you have more than 6 nodes, edit the templates/nginx-service.yaml to add more entries.
externalIp1:
externalIp2:
externalIp3:
externalIp4:
externalIp5:
externalIp6: