nsPrefix: onap
pullPolicy: Always 
nodePortPrefix: 302
image:
  readiness: oomk8s/readiness-check:1.0.0
  mso: elhaydox/mso:1.1.2_azure-1.0.0
  mariadb: nexus3.onap.org:10001/mariadb:10.1.11
  filebeat: docker.elastic.co/beats/filebeat:5.5.0
