#{{ if not .Values.disablePortalAeePortalIngress }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
#    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/ssl-redirect: "false"
#    ingress.kubernetes.io/configuration-snippet: |
#      more_set_headers "USER_ID: cs0008";
    ingress.kubernetes.io/server-snippet: |
      underscores_in_headers on;

  name: aee-sdc-ingress
  namespace: "{{ .Values.nsPrefix }}-sdc"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: sdc-fe
          servicePort: 8181
        path: /sdc1
      - backend:
          serviceName: sdc-fe
          servicePort: 8181
        path: /contextapp
      - backend:
          serviceName: sdc-fe
          servicePort: 8181
        path: /heat-validation
      - backend:
          serviceName: sdc-fe
          servicePort: 8181
        path: /onboarding
      - backend:
          serviceName: sdc-be
          servicePort: 8080
        path: /sdc2
      - backend:
          serviceName: sdc-be
          servicePort: 8080
        path: /onboarding-api
      - backend:
          serviceName: sdc-be
          servicePort: 8080
        path: /api-docs
#{{ end }}
