#{{ if not .Values.disableSdcSdcCs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: sdc-cs-create-dox-keyspace
  namespace: "{{ .Values.nsPrefix }}-sdc"
data:
{{ (.Files.Glob "resources/sdc-cs/chef-repo/cookbooks/cassandra-actions/templates/default/create_dox_keyspace.sh.erb").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sdc-cs-startup
  namespace: "{{ .Values.nsPrefix }}-sdc"
data:
{{ (.Files.Glob "resources/sdc-cs/startup.sh").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sdc-cs-recipes
  namespace: "{{ .Values.nsPrefix }}-sdc"
data:
{{ (.Files.Glob "resources/sdc-cs/chef-repo/cookbooks/cassandra-actions/recipes/*").AsConfig | indent 2 }}
#{{ end }}
#{{ if not .Values.disableSdcSdcBe }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sdc-be-startup
  namespace: "{{ .Values.nsPrefix }}-sdc"
data:
{{ (.Files.Glob "resources/sdc-be/startup.sh").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sdc-be-logback
  namespace: "{{ .Values.nsPrefix }}-sdc"
data:
{{ (.Files.Glob "resources/sdc-be/logconfig/logback.xml").AsConfig | indent 2 }}
#{{ end }}
#{{ if not .Values.disableSdcSdcFe }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sdc-fe-startup
  namespace: "{{ .Values.nsPrefix }}-sdc"
data:
{{ (.Files.Glob "resources/sdc-fe/startup.sh").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sdc-fe-logback
  namespace: "{{ .Values.nsPrefix }}-sdc"
data:
{{ (.Files.Glob "resources/sdc-fe/logconfig/logback.xml").AsConfig | indent 2 }}
#{{ end }}
