apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-prop
  namespace: {{ include "common.namespace" . }}
data:
{{ tpl (.Files.Glob "resources/config/model-loader.properties").AsConfig . | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-log
  namespace: {{ include "common.namespace" . }}
data:
{{ tpl (.Files.Glob "resources/config/log/logback.xml").AsConfig . | indent 2 }}
